### ISSUE TITLE
Suggestion: trim down text on first issue

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/write-github-script#4]
There's a lot of explanation on the first issue. I think we might have a better engagement rate with the course if we instead take the first PR as an opportunity to explain the script. I like the pattern of introducing a change, and then commenting with an explanation of what that change offers. The effect of this would look something like this:

<img width="821" alt="Screen Shot 2020-03-30 at 11 37 51 AM" src="https://user-images.githubusercontent.com/16547949/77932014-eca47980-727a-11ea-87b4-8269c617029f.png">

**Comment by hectorsector** [comment]
> Use the FS module to use a templated comment
> 
> We will make the following changes to the current workflow file:
> 
> Add the actions/checkout action so we can read the templated response file located at `.github/ISSUE_RESPONSES/comment.md`
> Add JavaScript to use the Node.js File System module to place the contents of our templated response as the body of the issue comment.

This is another example of a step that would be better in a suggested PR comment. Currently, it's explained, and the learner is asked to copy-and-paste a lot of code. It's a perfect opportunity to, instead, help them commit the code, and then use in-line comments to explain what just happened.

**Comment by mattdavis0351** [comment]
I would love to see the be a more data driven decision.  I really don't like seeing content split up because it makes it harder for me to see the full picture when it is.  That's a personal preference, as I feel like breaking it up is.

**Comment by mattdavis0351** [comment]
The flow I feel works best for courses is 

- issues explain the content
- pulls have learner practice the objective
- pull comments give feedback on learner practice

To me that's the flow that makes logical sense.

**Comment by hectorsector** [comment]
If we can come up with a way to test or A/B test this I'd be down. But for clarity, I think we're talking about 2 different things here:
1. Folks are likely to gloss over large blocks of text and this course has these large blocks right off the bat
2. Feedback being contextualized to code the learner is engaging with.

**Comment by mattdavis0351** [comment]
I would love to A/B test stuff like this.

I also think the position this course is in the learning path makes a difference.  If this was the first course in the path then I would agree with you 100%, but it's the exact opposite of that, it's the final course in the learning path.

So by the time they get here they will have quite the understanding of everything and where it works in the actions ecosystem.

It's also the "presentation" layer for our facilitator

**Comment by brianamarie** [comment]
A/B testing is something we've brought up in the past, but have never implemented as far as I know. @hectorsector @mattdavis0351 do you know if there is an issue open in `learning-lab` requesting this feature for course-authors?

**Comment by hectorsector** [comment]
I’ve moved this discussion over to https://github.com/github/learning-lab-content/issues/42 since we’re talking about general testing of assumptions, not just for this course. 

Feel free to close this issue if the decision is not to make these changes at this time!
